# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interviews_interventions.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    1   -1   -1    4    2    3    2    0  180 1500]
 [  85    3    1    0    2    1    3    1   34  150 1685]
 [  80    6   -2   -1    3    1    3    1   34  120 1670]
 [  80    6   -2   -2    2    1    2    1  119   90 1215]
 [  65    5   -2   -1    3    1    1    1    0   90 1595]
 [  90    2    0   -1    1    1    1    2   15   90   45]
 [  90    6   -2   -2    1    1    1    1    0   90 1400]
 [  85    2   -1   -1    1    3    1    1    0   90 1530]
 [  80    2   -1   -1    1    3    1    1    0   90 1170]
 [  85    3   -1   -1    1    2    1    1   12  120 1430]
 [  80    6   -2   -2    1    2    3    1   11    0 1245]
 [  80    3   -1   -1    2    2    4    2    0  180 1585]]


In [ ]:
print(y)

['N' 'N' 'N' 'N' 'D' 'D' 'N' 'N' 'M' 'M' 'M' 'N' 'N' 'N']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

In [ ]:
#print(y)

One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[  85,    3,   -1,   -1,    1,    2,    1,    1,   12,  120, 1430],
       [  80,    1,   -1,   -1,    4,    2,    3,    2,    0,  180, 1500],
       [  80,    3,   -1,   -1,    2,    2,    4,    2,    0,  180, 1585],
       [  85,    2,   -1,   -1,    1,    3,    1,    1,    0,   90, 1530],
       [  80,    5,    2,    2,    3,    3,    3,    3,   34,  150, 1710],
       [  90,    2,    0,   -1,    1,    1,    1,    2,   15,   90,   45],
       [  80,    2,   -1,   -1,    1,    3,    1,    1,    0,   90, 1170],
       [  85,    3,    1,    0,    2,    1,    3,    1,   34,  150, 1685],
       [  80,    5,    2,    2,    3,    3,    3,    3,   34,  150, 1710],
       [  80,    6,   -2,   -2,    2,    1,    2,    1,  119,   90, 1215],
       [  80,    6,   -2,   -2,    1,    2,    3,    1,   11,    0, 1245]])

In [ ]:
print(X_train.shape)
print(X_train[0].shape)
print(X_train[0])

(11, 11)
(11,)
[  85    3   -1   -1    1    2    1    1   12  120 1430]


### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1            # each feature is represented by 1 number

X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [ ]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

### Initializing the ANN

In [ ]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

In [ ]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
3/3 [==============================] - 3s 13ms/step - loss: 1.0932 - accuracy: 0.1818
Epoch 2/200
3/3 [==============================] - 0s 10ms/step - loss: 1.0599 - accuracy: 0.7273
Epoch 3/200
3/3 [==============================] - 0s 6ms/step - loss: 1.0335 - accuracy: 0.7273
Epoch 4/200
3/3 [==============================] - 0s 7ms/step - loss: 1.0130 - accuracy: 0.7273
Epoch 5/200
3/3 [==============================] - 0s 12ms/step - loss: 0.9888 - accuracy: 0.9091
Epoch 6/200
3/3 [==============================] - 0s 6ms/step - loss: 0.9622 - accuracy: 0.9091
Epoch 7/200
3/3 [==============================] - 0s 7ms/step - loss: 0.9292 - accuracy: 0.9091
Epoch 8/200
3/3 [==============================] - 0s 7ms/step - loss: 0.8919 - accuracy: 0.9091
Epoch 9/200
3/3 [==============================] - 0s 7ms/step - loss: 0.8450 - accuracy: 0.9091
Epoch 10/200
3/3 [==============================] - 0s 7ms/step - loss: 0.7962 - accuracy: 0.9091
Epoch 11/200
3/3 [========

## Part 4 - Making the predictions and evaluating the model

In [ ]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)


1/1 [==============================] - 1s 607ms/step - loss: 6.5259 - accuracy: 0.3333


[6.525856018066406, 0.3333333432674408]

### Predicting the Test set results

In [ ]:
y_pred = model.predict(X_test_reshaped)

1/1 [==============================] - 0s 220ms/step


In [ ]:
y_pred

array([[2.9468743e-05, 6.9922741e-08, 9.9997044e-01],
       [1.3283867e-04, 4.6659227e-07, 9.9986672e-01],
       [4.4978961e-02, 8.2351698e-04, 9.5419753e-01]], dtype=float32)

In [ ]:
y_predRounded= []
y_predEncoded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [ ]:
round(y_pred,y_predRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_predRounded)

0.3333333333333333

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_predRounded, average='weighted')

0.3333333333333333