# Artificial Neural Network

### Importing the libraries

In [1]:
from sklearn.neural_network import MLPClassifier
import tensorflow as tf
import pandas as pd
import numpy as np

In [2]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('interviews_interventions.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    5    2    2    3    3    3    3   34  150 1710]
 [  80    1   -1   -1    4    2    3    2    0  180 1500]
 [  85    3    1    0    2    1    3    1   34  150 1685]
 [  80    6   -2   -1    3    1    3    1   34  120 1670]
 [  80    6   -2   -2    2    1    2    1  119   90 1215]
 [  65    5   -2   -1    3    1    1    1    0   90 1595]
 [  90    2    0   -1    1    1    1    2   15   90   45]
 [  90    6   -2   -2    1    1    1    1    0   90 1400]
 [  85    2   -1   -1    1    3    1    1    0   90 1530]
 [  80    2   -1   -1    1    3    1    1    0   90 1170]
 [  85    3   -1   -1    1    2    1    1   12  120 1430]
 [  80    6   -2   -2    1    2    3    1   11    0 1245]
 [  80    3   -1   -1    2    2    4    2    0  180 1585]]


In [5]:
print(y)

['N' 'N' 'N' 'N' 'D' 'D' 'N' 'N' 'M' 'M' 'M' 'N' 'N' 'N']


### Encoding categorical data

In [6]:
y= np.array(y.reshape(len(y),1))

In [7]:
print(y)

[['N']
 ['N']
 ['N']
 ['N']
 ['D']
 ['D']
 ['N']
 ['N']
 ['M']
 ['M']
 ['M']
 ['N']
 ['N']
 ['N']]


One Hot Encoding the Y column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [9]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]])

### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [11]:
X_train

array([[  85,    3,   -1,   -1,    1,    2,    1,    1,   12,  120, 1430],
       [  80,    1,   -1,   -1,    4,    2,    3,    2,    0,  180, 1500],
       [  80,    3,   -1,   -1,    2,    2,    4,    2,    0,  180, 1585],
       [  85,    2,   -1,   -1,    1,    3,    1,    1,    0,   90, 1530],
       [  80,    5,    2,    2,    3,    3,    3,    3,   34,  150, 1710],
       [  90,    2,    0,   -1,    1,    1,    1,    2,   15,   90,   45],
       [  80,    2,   -1,   -1,    1,    3,    1,    1,    0,   90, 1170],
       [  85,    3,    1,    0,    2,    1,    3,    1,   34,  150, 1685],
       [  80,    5,    2,    2,    3,    3,    3,    3,   34,  150, 1710],
       [  80,    6,   -2,   -2,    2,    1,    2,    1,  119,   90, 1215],
       [  80,    6,   -2,   -2,    1,    2,    3,    1,   11,    0, 1245]])

### Feature Scaling

In [12]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [13]:
print(X_train)

[[ 0.83205029 -0.27196415 -0.46563307 -0.34836651 -0.91287093 -0.11470787
  -1.2094158  -0.82495791 -0.3492545   0.05423261  0.18180811]
 [-0.69337525 -1.46860639 -0.46563307 -0.34836651  2.09960314 -0.11470787
   0.69109474  0.47140452 -0.71225917  1.24735013  0.33649568]
 [-0.69337525 -0.27196415 -0.46563307 -0.34836651  0.09128709 -0.11470787
   1.64135001  0.47140452 -0.71225917  1.24735013  0.52433059]
 [ 0.83205029 -0.87028527 -0.46563307 -0.34836651 -0.91287093  1.14707867
  -1.2094158  -0.82495791 -0.71225917 -0.54232614  0.40279035]
 [-0.69337525  0.9246781   1.72949427  1.95085244  1.09544512  1.14707867
   0.69109474  1.76776695  0.31625407  0.65079137  0.80055838]
 [ 2.35747583 -0.87028527  0.26607604 -0.34836651 -0.91287093 -1.3764944
  -1.2094158   0.47140452 -0.25850333 -0.54232614 -2.8787959 ]
 [-0.69337525 -0.87028527 -0.46563307 -0.34836651 -0.91287093  1.14707867
  -1.2094158  -0.82495791 -0.71225917 -0.54232614 -0.39274571]
 [ 0.83205029 -0.27196415  0.99778516  0.4

In [14]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

## Part 2 - Building the MLP

### Initializing the MLP

In [15]:
clf = MLPClassifier(hidden_layer_sizes=(81,27,9,3),activation="relu",solver='adam', random_state=1)

## Part 3 - Training the MLP

### Training the MLP on the Training set

In [16]:
clf.fit(X_train, y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(


MLPClassifier(hidden_layer_sizes=(81, 27, 9, 3), random_state=1)

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [17]:
y_test_pred=clf.predict(X_test)

In [18]:
print(clf.score(X_test, y_test))


0.0


In [19]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_pred, average='weighted')

0.3333333333333333

In [20]:
y_test_pred

array([[1, 0, 1],
       [1, 0, 1],
       [1, 0, 1]])