# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [ ]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('interviews_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[   0    1    1 ...    0   90 1470]
 [  -1   -1    2 ...   24  120 1790]
 [   0   -1    2 ...   24   90 1545]
 ...
 [   0    0    1 ...   17   90  300]
 [  -1   -1    2 ...   26  120 1710]
 [   0   -1    1 ...   25   90 1500]]


In [ ]:
print(y)

['N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'M' 'M' 'N' 'M' 'N' 'N' 'M' 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'N'
 'N' 'M' 'M' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'M'
 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'N'
 'N' 'M' 'N' 'N' 'N' 'M' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'M' 'D' 'N' 'D'
 'N' 'D' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'D' 'D' 'N' 'N' 'D' 'D' 'D' 'N' 'N'
 'D' 'D' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'N'
 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'D' 'N' 'D' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'D'
 'D' 'D' 'D' 'N' 'D' 'N' 'D' 'N' 'D' 'D' 'N' 'D' 'D' 'D' 'N' 'N' 'N' 'D'
 'D' 'D' 'D' 'N' 'D' 'D' 'D' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'N' 'D' 'N' 'N'
 'N' 'D' 'N' 'D' 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'N' 'D' 'N' 'D' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'N' 'N' 'D' 'D'
 'N' 'N' 'N' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'N' 'N' 'D

### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

In [ ]:
#print(y)

One Hot Encoding the Y column

In [ ]:
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
y

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.]])

### Splitting the dataset into the Training set and Test set

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [ ]:
X_train

array([[  -1,    0,    2, ...,   34,   90, 1500],
       [  -1,   -1,    2, ...,   26,  120, 1515],
       [  -2,   -2,    1, ...,    0,   90, 1400],
       ...,
       [  -1,   -1,    3, ...,    0,   90, 1400],
       [   0,    0,    2, ...,   27,  150, 1870],
       [  -1,   -1,    1, ...,    0,   90, 1670]])

In [ ]:

print(X_train[0].shape)
print(X_train[0])

(9,)
[  -1    0    2    1    2    1   34   90 1500]


### Feature Scaling

In [ ]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train.shape)

(517, 9)


In [ ]:
sample_size = X_train.shape[0] # number of samples in train set
time_steps  = X_train.shape[1] # number of features in train set
input_dimension = 1            # each feature is represented by 1 number
X_train_reshaped = X_train.reshape(sample_size,time_steps,input_dimension)

In [ ]:
print(X_train_reshaped.shape)

(517, 9, 1)


In [ ]:
X_test_reshaped = X_test.reshape(X_test.shape[0],X_test.shape[1],1)

## Part 2 - Building the 1D-CNN

In [ ]:
n_timesteps = X_train_reshaped.shape[1]
n_features  = X_train_reshaped.shape[2]
model = tf.keras.Sequential()
model.add(tf.keras.layers.Input(shape=(n_timesteps,n_features)))
model.add(tf.keras.layers.Conv1D(filters=64, kernel_size=3, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=32, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.Conv1D(filters=16, kernel_size=2, activation='relu'))
model.add(tf.keras.layers.MaxPooling1D(pool_size=2))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(96, activation='relu'))
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(3, activation='softmax'))
model.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
model.fit(X_train_reshaped, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
104/104 [==============================] - 2s 2ms/step - loss: 0.9284 - accuracy: 0.5029
Epoch 2/200
104/104 [==============================] - 0s 2ms/step - loss: 0.7278 - accuracy: 0.7002
Epoch 3/200
104/104 [==============================] - 0s 2ms/step - loss: 0.6319 - accuracy: 0.7427
Epoch 4/200
104/104 [==============================] - 0s 2ms/step - loss: 0.5635 - accuracy: 0.7621
Epoch 5/200
104/104 [==============================] - 0s 2ms/step - loss: 0.5525 - accuracy: 0.7602
Epoch 6/200
104/104 [==============================] - 0s 2ms/step - loss: 0.5304 - accuracy: 0.7544
Epoch 7/200
104/104 [==============================] - 0s 3ms/step - loss: 0.5071 - accuracy: 0.7795
Epoch 8/200
104/104 [==============================] - 0s 2ms/step - loss: 0.4836 - accuracy: 0.7892
Epoch 9/200
104/104 [==============================] - 0s 2ms/step - loss: 0.4774 - accuracy: 0.7969
Epoch 10/200
104/104 [==============================] - 0s 2ms/step - loss: 0.4850 - accura

## Part 4 - Making the predictions and evaluating the model

In [ ]:
model.evaluate(X_test_reshaped,y_test,batch_size = 5)

26/26 [==============================] - 0s 2ms/step - loss: 1.5750 - accuracy: 0.7462


[1.575035810470581, 0.7461538314819336]

### Predicting the Test set results

In [ ]:
y_pred = model.predict(X_test_reshaped)

5/5 [==============================] - 0s 3ms/step


In [ ]:
y_pred

array([[5.44030309e-01, 3.15503925e-02, 4.24419314e-01],
       [7.03906044e-05, 5.65205664e-06, 9.99923885e-01],
       [2.50312775e-01, 9.20420687e-04, 7.48766840e-01],
       [6.46174958e-05, 9.96038361e-05, 9.99835730e-01],
       [9.47058976e-01, 1.36986182e-05, 5.29273637e-02],
       [9.04525369e-02, 5.52539706e-01, 3.57007831e-01],
       [9.04525369e-02, 5.52539706e-01, 3.57007831e-01],
       [5.60669345e-04, 5.82595894e-05, 9.99381125e-01],
       [2.85095048e-05, 1.41830742e-03, 9.98553216e-01],
       [7.90475962e-18, 2.75999797e-19, 9.99999940e-01],
       [2.32588601e-11, 1.22247980e-12, 9.99999940e-01],
       [6.46113217e-01, 1.84694567e-04, 3.53702098e-01],
       [1.61849603e-05, 2.62799176e-06, 9.99981105e-01],
       [1.88517603e-04, 7.79127222e-05, 9.99733567e-01],
       [1.01717005e-05, 2.99060417e-07, 9.99989450e-01],
       [1.99008409e-05, 2.43932300e-05, 9.99955595e-01],
       [9.99999940e-01, 1.82076424e-19, 2.01595365e-10],
       [2.01089471e-03, 3.97231

In [ ]:
ytest_predictionRounded= []
y_predEncoded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])


In [ ]:
round(y_pred,ytest_predictionRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, ytest_predictionRounded)

0.7461538461538462

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, ytest_predictionRounded, average='weighted')

0.74988344988345