# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [2]:
tf.__version__

'2.12.0'

### Importing the dataset

In [3]:
dataset = pd.read_csv('interviews_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[   0    1    1 ...    0   90 1470]
 [  -1   -1    2 ...   24  120 1790]
 [   0   -1    2 ...   24   90 1545]
 ...
 [   0    0    1 ...   17   90  300]
 [  -1   -1    2 ...   26  120 1710]
 [   0   -1    1 ...   25   90 1500]]


In [5]:
print(y)

['N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'M' 'M' 'N' 'M' 'N' 'N' 'M' 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'N'
 'N' 'M' 'M' 'N' 'M' 'N' 'N' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'M'
 'M' 'N' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'M' 'N'
 'N' 'M' 'N' 'N' 'N' 'M' 'M' 'N' 'N' 'M' 'N' 'N' 'N' 'N' 'M' 'D' 'N' 'D'
 'N' 'D' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'D' 'D' 'N' 'N' 'D' 'D' 'D' 'N' 'N'
 'D' 'D' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'N'
 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'D' 'N' 'D' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'D'
 'D' 'D' 'D' 'N' 'D' 'N' 'D' 'N' 'D' 'D' 'N' 'D' 'D' 'D' 'N' 'N' 'N' 'D'
 'D' 'D' 'D' 'N' 'D' 'D' 'D' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'N' 'D' 'N' 'N'
 'N' 'D' 'N' 'D' 'N' 'N' 'D' 'N' 'N' 'N' 'D' 'N' 'D' 'N' 'D' 'N' 'N' 'N'
 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N' 'N'
 'N' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'D' 'N' 'D' 'N' 'N' 'D' 'D'
 'N' 'N' 'N' 'D' 'N' 'N' 'D' 'D' 'N' 'N' 'N' 'N' 'D

### Encoding categorical data

In [6]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [7]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [8]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]


### Splitting the dataset into the Training set and Test set

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [11]:
print(X_train)

[[-0.35725437  0.80699977  0.44180447 ...  1.21397781 -0.15111299
   0.2553038 ]
 [-0.35725437 -0.18874935  0.44180447 ...  0.59248849  0.44617612
   0.29329223]
 [-1.33970389 -1.18449847 -0.97690927 ... -1.42735181 -0.15111299
   0.0020476 ]
 ...
 [-0.35725437 -0.18874935  1.86051822 ... -1.42735181 -0.15111299
   0.0020476 ]
 [ 0.62519515  0.80699977  0.44180447 ...  0.67017466  1.04346522
   1.19235175]
 [-0.35725437 -0.18874935 -0.97690927 ... -1.42735181 -0.15111299
   0.68583935]]


In [12]:
print(y_train)

[[1. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 ...
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [13]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [14]:

ann.add(tf.keras.layers.Dense(units=81, activation='relu'))

In [15]:
ann.add(tf.keras.layers.Dense(units=27, activation='relu'))
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))


### Adding the output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [18]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
104/104 [==============================] - 1s 2ms/step - loss: 0.9492 - accuracy: 0.6093
Epoch 2/200
104/104 [==============================] - 0s 2ms/step - loss: 0.6941 - accuracy: 0.7060
Epoch 3/200
104/104 [==============================] - 0s 1ms/step - loss: 0.5879 - accuracy: 0.7621
Epoch 4/200
104/104 [==============================] - 0s 1ms/step - loss: 0.5403 - accuracy: 0.7872
Epoch 5/200
104/104 [==============================] - 0s 1ms/step - loss: 0.5081 - accuracy: 0.7756
Epoch 6/200
104/104 [==============================] - 0s 1ms/step - loss: 0.4742 - accuracy: 0.8066
Epoch 7/200
104/104 [==============================] - 0s 1ms/step - loss: 0.4613 - accuracy: 0.8066
Epoch 8/200
104/104 [==============================] - 0s 1ms/step - loss: 0.4417 - accuracy: 0.8201
Epoch 9/200
104/104 [==============================] - 0s 1ms/step - loss: 0.4264 - accuracy: 0.8221
Epoch 10/200
104/104 [==============================] - 0s 1ms/step - loss: 0.4202 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [19]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

17/17 [==============================] - 0s 1ms/step


In [20]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [21]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])



In [22]:
round(ytest_pred,y_test_predRounded)

In [23]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.7461538461538462

In [24]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='weighted')

0.749651436039132