# Artificial Neural Network

## Part 1 - Data Preprocessing

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf
from sklearn.metrics import classification_report

In [ ]:
tf.__version__

'2.12.0'

### Importing the dataset

In [ ]:
dataset = pd.read_csv('ymrs_episodes.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[0 1 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 0 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [0 1 0 0 0 2 0 0 2 0 0]
 [1 1 0 0 0 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 2 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 2 0 0]
 [1 0 0 0 2 2 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 2 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 2 0 0 2 0 0]
 [0 0 0 0 2 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]


In [ ]:
print(y)

['N' 'N' 'M' 'M' 'N' 'N' 'N' 'N' 'D' 'N' 'D' 'D' 'N' 'N' 'N' 'D' 'N' 'N'
 'M' 'D' 'N' 'D' 'M' 'D' 'M' 'N' 'N' 'M' 'D' 'N' 'N' 'N' 'D' 'N' 'D']


### Encoding categorical data

In [ ]:
y= np.array(y.reshape(len(y),1))

One Hot Encoding the Y column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])])
y = np.array(ct.fit_transform(y))

In [ ]:
print(y)

[[0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [ ]:
print(X_train)

[[-0.2773501   1.60451491  0.          0.         -0.63245553  1.73205081
  -0.19245009  0.          2.44948974  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.          1.58113883 -0.57735027
   5.19615242  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.         -0.63245553 -0.57735027
  -0.19245009  0.         -0.40824829  0.          0.        ]
 [-0.2773501  -0.43759497  0.          0.

In [ ]:
print(y_train)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:

ann.add(tf.keras.layers.Dense(units=81, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=27, activation='relu'))
ann.add(tf.keras.layers.Dense(units=9, activation='relu'))


### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=3, activation='softmax'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size = 5, epochs = 200)

Epoch 1/200
6/6 [==============================] - 3s 10ms/step - loss: 1.0556 - accuracy: 0.5714
Epoch 2/200
6/6 [==============================] - 0s 7ms/step - loss: 1.0227 - accuracy: 0.5714
Epoch 3/200
6/6 [==============================] - 0s 6ms/step - loss: 0.9945 - accuracy: 0.5714
Epoch 4/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9695 - accuracy: 0.5714
Epoch 5/200
6/6 [==============================] - 0s 4ms/step - loss: 0.9509 - accuracy: 0.5714
Epoch 6/200
6/6 [==============================] - 0s 5ms/step - loss: 0.9319 - accuracy: 0.6071
Epoch 7/200
6/6 [==============================] - 0s 6ms/step - loss: 0.9122 - accuracy: 0.6071
Epoch 8/200
6/6 [==============================] - 0s 4ms/step - loss: 0.8938 - accuracy: 0.6071
Epoch 9/200
6/6 [==============================] - 0s 11ms/step - loss: 0.8770 - accuracy: 0.6071
Epoch 10/200
6/6 [==============================] - 0s 6ms/step - loss: 0.8621 - accuracy: 0.6429
Epoch 11/200
6/6 [=========

## Part 4 - Making the predictions and evaluating the model

### Predicting the Test set results

In [ ]:
ytest_pred = ann.predict(X_test)
ytrain_pred = ann.predict(X_train)

1/1 [==============================] - 0s 23ms/step


In [ ]:
y_test_predRounded= []
y_test_predEncoded = []
ytrain_pred= []
ytrain_predRoundeded = []


In [ ]:
def round(predicted,rounded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      rounded.append([1.,0.,0.])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      rounded.append([0.,1.,0.])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      rounded.append([0.,0.,1.])
    else:
      rounded.append([0.,0.,1.])

def encode(predicted,encoded):
  for i in range(len(predicted)):
    if predicted[i,0] >  predicted[i,1] and predicted[i,0] >  predicted[i,2]:
      encoded.append(['D'])
    elif predicted[i,1] >  predicted[i,0] and predicted[i,1] >  predicted[i,2]:
      encoded.append(['M'])
    elif predicted[i,2] >  predicted[i,0] and predicted[i,2] >  predicted[i,1]:
      encoded.append(['N'])
    else:
      encoded.append(['N'])



In [ ]:
round(ytest_pred,y_test_predRounded)

In [ ]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_test_predRounded)

0.5714285714285714

In [ ]:
from sklearn.metrics import f1_score
f1_score(y_test, y_test_predRounded, average='weighted')

0.4928571428571428